name: 📦 Raw Material (Paper)
description: Capture a new research paper.
title: "[Paper]: Title"
labels: ["type: paper"]
body:
  - type: input
    id: link
    attributes:
      label: Link / Source
      placeholder: https://arxiv.org/abs/...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Abstract / Thoughts
      description: Paste the abstract or your initial "why" here. Saves you a click later.
      placeholder: "This paper proposes a new method for..."
    validations:
      required: false
